import { NextResponse } from 'next/server';

interface TrendingProduct {
  id: string;
  name: string;
  description: string;
  priceCents: number;
  category: string;
  inStock: boolean;
  imageUrls: string[];
  createdAt: string;
  updatedAt: string;
  sourceUrl: string;
  supplierCostCents: number;
  source: 'cj' | 'aliexpress';
  trendScore: 'hot' | 'rising' | 'stable';
  repeatPurchase: boolean;
  viralPlatform?: 'tiktok' | 'instagram' | 'youtube';
}

/**
 * TOP 20 PRODUITS VALIDÉS 2026
 * Basé sur la demande réelle, viral social, et repeat purchase
 */
const TRENDING_2026_CATALOG: TrendingProduct[] = [
  // 🧠 BEAUTY / SKINCARE (catégorie #1 - repeat purchase massif)
  {
    id: 'trend-kojic-acid-serum',
    name: 'Kojic Acid Serum - Anti-Taches',
    description: 'Sérum anti-taches à l\'acide kojique. Réduit visiblement les taches brunes et unifie le teint. Résultats visibles en 2-4 semaines. Formule concentrée 2%.',
    priceCents: 2990,
    supplierCostCents: 890,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/kojic-acid-serum.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: true,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-bakuchiol-serum',
    name: 'Bakuchiol Serum - Alternative Retinol',
    description: 'Alternative naturelle au rétinol, sans irritation. Anti-rides, raffermissant, convient aux peaux sensibles. Bakuchiol 1% + acide hyaluronique.',
    priceCents: 3490,
    supplierCostCents: 1050,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/bakuchiol-serum.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: true,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-pdrn-serum',
    name: 'PDRN Serum - K-Beauty Viral',
    description: 'Sérum PDRN (Polydésoxyribonucléotide) - régénération cellulaire intense. Viral K-beauty, réduit rides et cicatrices. Formule coréenne premium.',
    priceCents: 4990,
    supplierCostCents: 1490,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/pdrn-serum.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: true,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-under-eye-patches',
    name: 'Under Eye Patches - Anti-Cernes',
    description: 'Patchs hydrogel anti-cernes et anti-poches. Acide hyaluronique + collagène + vitamine C. Résultats immédiats. Boîte de 60 patchs (30 paires).',
    priceCents: 1990,
    supplierCostCents: 590,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/under-eye-patches.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: true,
    viralPlatform: 'instagram',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-microneedle-patches',
    name: 'Microneedle Patches - Acné & Rides',
    description: 'Patchs micro-aiguilles pour acné et rides. Technologie dissolvante, pénétration profonde des actifs. Acide hyaluronique + niacinamide. 24 patchs.',
    priceCents: 2490,
    supplierCostCents: 740,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/microneedle-patches.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: true,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-barrier-repair-cream',
    name: 'Barrier Repair Cream - Peau Sensible',
    description: 'Crème réparatrice de barrière cutanée. Céramides + cholestérol + acides gras. Idéale peau sensible, irritée, rosacée. Formule minimaliste.',
    priceCents: 2790,
    supplierCostCents: 830,
    category: 'Beauty & Skincare',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/barrier-repair-cream.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 💆 WELLNESS / SANTÉ MAISON
  {
    id: 'trend-red-light-therapy-belt',
    name: 'Red Light Therapy Belt - LED Thérapie',
    description: 'Ceinture thérapie LED rouge et infrarouge. Soulage douleurs musculaires, améliore circulation. 660nm + 850nm. Portable, rechargeable USB.',
    priceCents: 8990,
    supplierCostCents: 2690,
    category: 'Wellness & Health',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/red-light-therapy-belt.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-deep-tissue-massager',
    name: 'Deep Tissue Massager - Massage Gun Pro',
    description: 'Pistolet de massage professionnel. 30 vitesses, 8 têtes interchangeables, écran LCD. Batterie 6h. Soulage tensions musculaires profondes.',
    priceCents: 6990,
    supplierCostCents: 2090,
    category: 'Wellness & Health',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/deep-tissue-massager.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-toe-spacers',
    name: 'Toe Spacers - Alignement Pieds',
    description: 'Écarteurs d\'orteils en silicone médical. Corrige hallux valgus, soulage douleurs pieds. Utilisable jour/nuit. Lot de 2 paires.',
    priceCents: 1490,
    supplierCostCents: 440,
    category: 'Wellness & Health',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/toe-spacers.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: false,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-anti-snoring-mouthpiece',
    name: 'Anti-Snoring Mouthpiece - Stop Ronflement',
    description: 'Orthèse anti-ronflement ajustable. Avance la mâchoire, libère les voies respiratoires. Silicone médical sans BPA. Boîtier de rangement inclus.',
    priceCents: 2990,
    supplierCostCents: 890,
    category: 'Wellness & Health',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/anti-snoring-mouthpiece.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🏠 PRODUITS UTILES MAISON
  {
    id: 'trend-rain-cloud-humidifier',
    name: 'Rain Cloud Humidifier - Diffuseur Viral',
    description: 'Humidificateur diffuseur design nuage avec effet pluie. LED 7 couleurs, brumisation silencieuse. Viral TikTok. Capacité 300ml, autonomie 8h.',
    priceCents: 3490,
    supplierCostCents: 1040,
    category: 'Home & Living',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/rain-cloud-humidifier.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: false,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-smart-led-motion-light',
    name: 'Smart LED Motion Light - Détecteur Mouvement',
    description: 'Veilleuse LED avec détecteur de mouvement. Rechargeable USB, bande magnétique. Idéale escaliers, placards, couloirs. Lot de 3.',
    priceCents: 2490,
    supplierCostCents: 740,
    category: 'Home & Living',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/smart-led-motion-light.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-kitchen-organizer',
    name: 'Kitchen Organizer - Rangement Cuisine',
    description: 'Organisateur cuisine multifonction. Tiroirs coulissants, compartiments modulables. Gain de place garanti. Matériaux durables, facile à nettoyer.',
    priceCents: 3990,
    supplierCostCents: 1190,
    category: 'Home & Living',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/kitchen-organizer.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-pillow-stand',
    name: 'Pillow Stand - Support Tablette/Téléphone',
    description: 'Support coussin multi-angles pour tablette et téléphone. Confort optimal au lit, canapé. Tissu doux, base stable. Compatible tous appareils.',
    priceCents: 1990,
    supplierCostCents: 590,
    category: 'Home & Living',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/pillow-stand.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 📱 TECH / VIRAL VISUEL
  {
    id: 'trend-mini-retro-camera',
    name: 'Mini Retro Digital Camera - Keychain Cam',
    description: 'Mini caméra digitale rétro porte-clés. 1080p, écran 2", filtre vintage. Viral TikTok/Instagram. Batterie 2h, carte SD incluse.',
    priceCents: 2990,
    supplierCostCents: 890,
    category: 'Tech & Gadgets',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/mini-retro-camera.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: false,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-magnetic-power-bank',
    name: 'Magnetic Power Bank - Batterie MagSafe',
    description: 'Batterie externe magnétique 10000mAh. Compatible MagSafe iPhone 12+. Charge sans fil 15W. Ultra-fin, LED indicateur. USB-C PD 20W.',
    priceCents: 3990,
    supplierCostCents: 1190,
    category: 'Tech & Gadgets',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/magnetic-power-bank.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-wireless-lavalier-mic',
    name: 'Wireless Lavalier Mic - Micro Créateurs',
    description: 'Micro-cravate sans fil pour créateurs de contenu. Réduction bruit AI, portée 50m. Compatible iPhone/Android. Batterie 8h. Boîtier de charge.',
    priceCents: 4990,
    supplierCostCents: 1490,
    category: 'Tech & Gadgets',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/wireless-lavalier-mic.html',
    source: 'aliexpress',
    trendScore: 'hot',
    repeatPurchase: false,
    viralPlatform: 'youtube',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 🐶 PET PRODUCTS
  {
    id: 'trend-self-cleaning-pet-brush',
    name: 'Self-Cleaning Pet Brush - Brosse Auto-Nettoyante',
    description: 'Brosse autonettoyante pour chiens et chats. Bouton éjection poils, picots doux. Réduit mue de 95%. Ergonomique, anti-dérapante.',
    priceCents: 1990,
    supplierCostCents: 590,
    category: 'Pet Supplies',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/self-cleaning-pet-brush.html',
    source: 'aliexpress',
    trendScore: 'stable',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-pet-water-fountain',
    name: 'Pet Water Fountain - Fontaine à Eau',
    description: 'Fontaine à eau pour animaux 2L. Triple filtration, ultra-silencieuse. Encourage hydratation. LED indicateur niveau. Facile à nettoyer.',
    priceCents: 2990,
    supplierCostCents: 890,
    category: 'Pet Supplies',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/pet-water-fountain.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trend-interactive-pet-toy',
    name: 'Interactive Pet Toy - Jouet Anti-Ennui',
    description: 'Jouet interactif intelligent pour chiens/chats. Mouvements aléatoires, sons, LED. Stimulation mentale, combat l\'ennui. Rechargeable USB.',
    priceCents: 2490,
    supplierCostCents: 740,
    category: 'Pet Supplies',
    inStock: true,
    imageUrls: [],
    sourceUrl: 'https://www.aliexpress.com/item/interactive-pet-toy.html',
    source: 'aliexpress',
    trendScore: 'rising',
    repeatPurchase: false,
    viralPlatform: 'tiktok',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const CATALOG_STATS = {
  totalProducts: TRENDING_2026_CATALOG.length,
  categories: {
    'Beauty & Skincare': 6,
    'Wellness & Health': 4,
    'Home & Living': 4,
    'Tech & Gadgets': 3,
    'Pet Supplies': 3,
  },
  trendScores: {
    hot: TRENDING_2026_CATALOG.filter(p => p.trendScore === 'hot').length,
    rising: TRENDING_2026_CATALOG.filter(p => p.trendScore === 'rising').length,
    stable: TRENDING_2026_CATALOG.filter(p => p.trendScore === 'stable').length,
  },
  repeatPurchase: TRENDING_2026_CATALOG.filter(p => p.repeatPurchase).length,
  avgMargin: Math.round(
    TRENDING_2026_CATALOG.reduce((sum, p) => sum + ((p.priceCents - p.supplierCostCents) / p.priceCents) * 100, 0) /
      TRENDING_2026_CATALOG.length
  ),
};

export async function GET() {
  return NextResponse.json({
    catalog: TRENDING_2026_CATALOG,
    stats: CATALOG_STATS,
  });
}
