-- P0.4: ad copy variants per product.
-- For each product the agent can fan out 3 hooks (Meta, TikTok, Google
-- style) that the founder copy-pastes into the respective ad managers.
-- Visuals come from the existing mono-asset pipeline (hero / cutout /
-- lifestyles / promo) so we don't re-bill GPU for what we already have.
--
-- Idempotent.

CREATE TABLE IF NOT EXISTS dropship_ad_variants (
  id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id      UUID         NOT NULL REFERENCES dropship_stores(id) ON DELETE CASCADE,
  product_id    UUID         NOT NULL REFERENCES dropship_store_products(id) ON DELETE CASCADE,
  batch_id      text         NOT NULL,
  channel       text         NOT NULL CHECK (channel IN ('meta', 'tiktok', 'google')),
  headline      text         NOT NULL,
  primary_text  text         NOT NULL,
  description   text         NULL,
  cta           text         NULL,
  meta          jsonb        NULL,
  created_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dropship_ad_variants_store_idx
  ON dropship_ad_variants(store_id, created_at DESC);

CREATE INDEX IF NOT EXISTS dropship_ad_variants_product_idx
  ON dropship_ad_variants(product_id, created_at DESC);

CREATE INDEX IF NOT EXISTS dropship_ad_variants_batch_idx
  ON dropship_ad_variants(batch_id);

COMMENT ON TABLE dropship_ad_variants IS
  'P0.4 Phase 1 — ad copy variants generated by Claude per product, per channel.';
