-- 024_landing_content.sql
-- Structured copy for storefront templates so we never re-leak
-- product-specific demo content (see "Brisa ventilator" incident).
--
-- The agent (Haiku, called from store-creator after product enrichment)
-- writes this object once at store creation time. Templates read it at
-- render time, with a generic fallback for any field that's missing.
--
-- Shape (all fields optional, partial fills are fine):
-- {
--   "hero": {
--     "kicker": "Nouveau · 2026",
--     "headline_html": "Du <em>silence</em> autour du cou.",
--     "lede": "Un texte court, 1-2 phrases concrètes."
--   },
--   "selling_points": [
--     { "title": "...", "body": "..." }, ... 3 items
--   ],
--   "showcase": { "kicker": "...", "headline_html": "...", "lede": "..." },
--   "beach_moment": { "kicker": "...", "headline_html": "..." },
--   "specs": [ { "key": "Autonomie", "value": "8h" }, ... 6-10 items ],
--   "trust_promises": [
--     { "title": "Expédition 24h", "body": "..." }, ... 3 items
--   ],
--   "included_items": [ { "qty": "01", "label": "..." }, ... 4 items ],
--   "final_cta": { "kicker": "...", "headline_html": "...", "lede": "..." }
-- }

ALTER TABLE dropship_stores
  ADD COLUMN IF NOT EXISTS landing_content jsonb;

COMMENT ON COLUMN dropship_stores.landing_content IS
  'Structured copy for storefront templates. Generated by the agent at store creation. See 024_landing_content.sql for the shape.';
