import type { DesignSystem } from '../types';

export const ds06: DesignSystem = {
  id: 'ds-06',
  num: '06',
  name: 'Luxury Gold',
  category: 'luxury',
  description: 'Black and gold, premium and opulent',
  audience: ['bijoux', 'montres', 'luxe', 'premium', 'accessoires', 'maroquinerie'],
  darkMode: true,
  colors: {
    accent: '#d4a843',
    bg: '#0c0c0c',
    bgAlt: '#1a1a1a',
    text: '#f5f5f0',
    textSecondary: '#b8860b',
    textMuted: '#a3a3a3',
    border: '#333333',
  },
  typography: {
    fontPrimary: "'Cormorant Garamond', serif",
    fontBody: "'Montserrat', sans-serif",
    sizeH1: '4rem',
    sizeH2: '3rem',
    sizeH3: '2rem',
    sizeBody: '1rem',
    weightBlack: '900',
    weightBold: '700',
    weightRegular: '400',
    letterSpacingWide: '0.1em',
  },
  spacing: { sm: '0.75rem', md: '1.5rem', lg: '3rem', xl: '6rem' },
  components: {
    borderWidth: '1px',
    radius: '0rem',
    shadow: '0 8px 24px rgba(212, 168, 67, 0.15)',
    transition: '0.3s ease',
    btnPadding: '1rem 2.5rem',
  },
};
