import type { DesignSystem } from '../types';

export const ds07: DesignSystem = {
  id: 'ds-07',
  num: '07',
  name: 'Sport Energy',
  category: 'sport',
  description: 'Dynamic red/black for high-energy sports',
  audience: ['sport', 'fitness', 'outdoor', 'running', 'musculation', 'nutrition'],
  darkMode: true,
  colors: {
    accent: '#dc2626',
    bg: '#0f0f0f',
    bgAlt: '#1c1c1c',
    text: '#fafafa',
    textSecondary: '#f97316',
    textMuted: '#a3a3a3',
    border: '#404040',
  },
  typography: {
    fontPrimary: "'Bebas Neue', sans-serif",
    fontBody: "'Barlow', sans-serif",
    sizeH1: '4.5rem',
    sizeH2: '3rem',
    sizeH3: '2rem',
    sizeBody: '1.1rem',
    weightBlack: '900',
    weightBold: '700',
    weightRegular: '400',
    letterSpacingWide: '0.05em',
  },
  spacing: { sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem' },
  components: {
    borderWidth: '2px',
    radius: '0.25rem',
    shadow: '0 4px 16px rgba(220, 38, 38, 0.3)',
    transition: '0.2s ease',
    btnPadding: '1rem 2rem',
  },
};
