import type { DesignSystem } from '../types';

export const ds10: DesignSystem = {
  id: 'ds-10',
  num: '10',
  name: 'Streetwear',
  category: 'fashion',
  description: 'Urban, graffiti-inspired, bold and raw',
  audience: ['streetwear', 'sneakers', 'urban', 'hip-hop', 'skate', 'mode-urbaine'],
  darkMode: true,
  colors: {
    accent: '#facc15',
    bg: '#111111',
    bgAlt: '#1e1e1e',
    text: '#f5f5f5',
    textSecondary: '#f43f5e',
    textMuted: '#a3a3a3',
    border: '#404040',
  },
  typography: {
    fontPrimary: "'Anton', sans-serif",
    fontBody: "'Rubik', sans-serif",
    sizeH1: '4.5rem',
    sizeH2: '3rem',
    sizeH3: '2rem',
    sizeBody: '1.1rem',
    weightBlack: '900',
    weightBold: '700',
    weightRegular: '400',
    letterSpacingWide: '0.05em',
  },
  spacing: { sm: '0.5rem', md: '1rem', lg: '2rem', xl: '4rem' },
  components: {
    borderWidth: '3px',
    radius: '0rem',
    shadow: '8px 8px 0 rgba(250, 204, 21, 0.3)',
    transition: '0.2s ease',
    btnPadding: '1rem 2rem',
  },
};
