#!/usr/bin/env tsx

import { generateFromTemplateFast, generateFromTemplate, getTemplate } from './src/index';
import type { EcommerceSiteConfig, TemplateVars } from './src/index';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

async function testPureTemplate() {
  console.log('\n🧪 Test 1: Pure Template (no LLM)');
  console.log('=====================================');
  
  const template = getTemplate('anime');
  if (!template) {
    console.error('❌ Template anime not found');
    return;
  }

  const vars: TemplateVars = {
    brandName: 'AnimeStore',
    tagline: 'Your favorite anime merch',
    niche: 'anime',
    products: [
      { name: 'Naruto Figure', price: 29.99, handle: 'naruto-figure' },
      { name: 'One Piece Poster', price: 19.99, handle: 'one-piece-poster' },
      { name: 'Attack on Titan Hoodie', price: 49.99, handle: 'aot-hoodie' },
    ],
  };

  const start = Date.now();
  const files = generateFromTemplate(template, vars);
  const duration = Date.now() - start;

  console.log(`✅ Generated ${files.size} pages in ${duration}ms`);
  
  for (const [path, code] of files) {
    console.log(`  - ${path}: ${code.length} chars, ${code.split('\n').length} lines`);
    
    // Validation basique
    if (!code.includes('export default')) {
      console.warn(`    ⚠️  Missing "export default" in ${path}`);
    }
    if ((path.includes('page.tsx') && !path.includes('about') && !path.includes('contact')) && !code.includes('getProducts')) {
      console.warn(`    ⚠️  Missing "getProducts" in ${path}`);
    }
  }

  // Sauvegarder dans un dossier de test
  const outputDir = './test-output/pure-template';
  await mkdir(outputDir, { recursive: true });
  
  for (const [filePath, code] of files) {
    const fileName = filePath.replace(/\//g, '_').replace(/^_/, '');
    await writeFile(join(outputDir, fileName), code, 'utf-8');
  }
  
  console.log(`📁 Files saved to ${outputDir}`);
}

async function testTemplateWithLLM() {
  console.log('\n🧪 Test 2: Template + LLM (fast mode)');
  console.log('=====================================');
  
  const config: EcommerceSiteConfig = {
    brandName: 'LuxuryWatches',
    tagline: '', // Will be generated by LLM
    niche: 'luxury watches',
    tone: 'premium',
    palette: 'dark',
    typography: 'modern',
    products: [
      { name: 'Rolex Submariner', price: 8999.99 },
      { name: 'Omega Seamaster', price: 6499.99 },
      { name: 'Tag Heuer Carrera', price: 4999.99 },
    ],
    pages: [],
  };

  const start = Date.now();
  const files = await generateFromTemplateFast(config, undefined, (step, detail) => {
    console.log(`  [${step}] ${detail}`);
  });
  const duration = Date.now() - start;

  console.log(`✅ Generated ${files.size} pages in ${duration}ms`);
  
  for (const [path, code] of files) {
    console.log(`  - ${path}: ${code.length} chars`);
  }

  // Sauvegarder
  const outputDir = './test-output/template-with-llm';
  await mkdir(outputDir, { recursive: true });
  
  for (const [filePath, code] of files) {
    const fileName = filePath.replace(/\//g, '_').replace(/^_/, '');
    await writeFile(join(outputDir, fileName), code, 'utf-8');
  }
  
  console.log(`📁 Files saved to ${outputDir}`);
}

async function testAllTemplates() {
  console.log('\n🧪 Test 3: All Templates');
  console.log('=====================================');
  
  const templates = ['anime', 'luxury', 'streetwear', 'beauty', 'tech', 'general'];
  
  for (const templateId of templates) {
    const template = getTemplate(templateId);
    if (!template) {
      console.error(`❌ Template ${templateId} not found`);
      continue;
    }

    const vars: TemplateVars = {
      brandName: `Test${templateId.charAt(0).toUpperCase() + templateId.slice(1)}`,
      tagline: `Premium ${template.niches[0]} products`,
      niche: template.niches[0] || 'general',
      products: [
        { name: 'Product 1', price: 29.99, handle: 'product-1' },
        { name: 'Product 2', price: 49.99, handle: 'product-2' },
      ],
    };

    const start = Date.now();
    const files = generateFromTemplate(template, vars);
    const duration = Date.now() - start;

    const totalChars = Array.from(files.values()).reduce((sum, code) => sum + code.length, 0);
    console.log(`  ${templateId.padEnd(12)} → ${files.size} pages, ${totalChars} chars, ${duration}ms`);

    // Sauvegarder
    const outputDir = `./test-output/all-templates/${templateId}`;
    await mkdir(outputDir, { recursive: true });
    
    for (const [filePath, code] of files) {
      const fileName = filePath.replace(/\//g, '_').replace(/^_/, '');
      await writeFile(join(outputDir, fileName), code, 'utf-8');
    }
  }
  
  console.log(`📁 All templates saved to ./test-output/all-templates/`);
}

async function testTemplateValidation() {
  console.log('\n🧪 Test 4: Template Validation');
  console.log('=====================================');
  
  const templates = ['anime', 'luxury', 'streetwear', 'beauty', 'tech', 'general'];
  const issues: string[] = [];
  
  for (const templateId of templates) {
    const template = getTemplate(templateId);
    if (!template) {
      issues.push(`❌ Template ${templateId} not found`);
      continue;
    }

    console.log(`\nValidating ${templateId}...`);

    // Check structure
    if (!template.id || !template.name || !template.niches || !template.pages) {
      issues.push(`❌ ${templateId}: Missing required fields`);
    }

    if (template.niches.length === 0) {
      issues.push(`⚠️  ${templateId}: No niches defined`);
    }

    const expectedPages = ['/', '/shop', '/about', '/contact'];
    for (const page of expectedPages) {
      if (!template.pages[page]) {
        issues.push(`❌ ${templateId}: Missing page ${page}`);
      }
    }

    // Test each page generator
    const vars: TemplateVars = {
      brandName: 'TestBrand',
      tagline: 'Test tagline',
      niche: template.niches[0] || 'general',
      products: [
        { name: 'Product 1', price: 29.99, handle: 'product-1' },
      ],
    };

    for (const [route, generator] of Object.entries(template.pages)) {
      try {
        const code = generator(vars);
        
        // Validation checks
        if (!code.includes('export default')) {
          issues.push(`⚠️  ${templateId} ${route}: Missing "export default"`);
        }

        if (route === '/' || route === '/shop') {
          if (!code.includes('getProducts')) {
            issues.push(`⚠️  ${templateId} ${route}: Missing "getProducts" import`);
          }
        }

        if (route === '/contact') {
          if (!code.includes("'use client'")) {
            issues.push(`⚠️  ${templateId} ${route}: Missing "use client" directive`);
          }
        }

        if (!code.includes(vars.brandName)) {
          issues.push(`⚠️  ${templateId} ${route}: Brand name not used`);
        }

        if (code.length < 500) {
          issues.push(`⚠️  ${templateId} ${route}: Code too short (${code.length} chars)`);
        }

        console.log(`  ✅ ${route}: ${code.length} chars`);
      } catch (err) {
        issues.push(`❌ ${templateId} ${route}: Generator failed - ${err}`);
      }
    }
  }

  console.log('\n📊 Validation Summary');
  console.log('=====================');
  
  if (issues.length === 0) {
    console.log('✅ All templates are valid!');
  } else {
    console.log(`Found ${issues.length} issues:\n`);
    for (const issue of issues) {
      console.log(issue);
    }
  }
}

async function main() {
  console.log('🚀 Starting comprehensive template tests...\n');

  try {
    await testPureTemplate();
    await testTemplateWithLLM();
    await testAllTemplates();
    await testTemplateValidation();

    console.log('\n✅ All tests completed!');
  } catch (err) {
    console.error('\n❌ Test failed:', err);
    process.exit(1);
  }
}

main();
