'use client';

import { useEffect, useState } from 'react';

interface Campaign {
  id: string;
  site_id: string;
  platform: string;
  name: string;
  daily_budget: number | null;
  status: string;
  metrics: Record<string, unknown>;
  targeting?: Record<string, unknown>;
  creatives?: Record<string, unknown>;
  created_at?: string;
}

interface Site {
  id: string;
  name: string;
}

export default function MarketingPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [sites, setSites] = useState<Map<string, string>>(new Map());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetch('/api/campaigns').then(r => r.json()).then(d => d.campaigns ?? []),
      fetch('/api/sites').then(r => r.json()).then(d => d.sites ?? []),
    ]).then(([camps, allSites]: [Campaign[], Site[]]) => {
      setCampaigns(camps);
      const m = new Map<string, string>();
      allSites.forEach((s: Site) => m.set(s.id, s.name));
      setSites(m);
    }).catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const googleAds = campaigns.filter(c => c.platform === 'google_ads');
  const metaAds = campaigns.filter(c => c.platform === 'meta');
  const totalBudget = campaigns.reduce((sum, c) => sum + (c.daily_budget ?? 0), 0);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Marketing</h2>
      </div>

      <div className="grid gap-4 sm:grid-cols-4">
        <StatCard label="Total Campaigns" value={String(campaigns.length)} />
        <StatCard label="Google Ads" value={String(googleAds.length)} />
        <StatCard label="Meta Ads" value={String(metaAds.length)} />
        <StatCard label="Daily Budget" value={`$${(totalBudget / 100).toFixed(0)}`} />
      </div>

      {loading ? (
        <div className="h-40 animate-pulse rounded-xl bg-gray-100" />
      ) : campaigns.length === 0 ? (
        <div className="rounded-xl border-2 border-dashed p-12 text-center text-gray-500">
          <p className="text-lg">No campaigns yet</p>
          <p className="mt-1 text-sm">Campaigns are automatically generated by the A-Z pipeline</p>
        </div>
      ) : (
        <div className="space-y-3">
          {campaigns.map(c => (
            <div key={c.id} className="rounded-xl border bg-white p-5 shadow-sm">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold">{c.name}</h3>
                  <p className="text-sm text-gray-500">
                    {sites.get(c.site_id) ?? c.site_id.slice(0, 8)} · {c.platform === 'google_ads' ? 'Google Ads' : c.platform === 'meta' ? 'Meta Ads' : c.platform}
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  {c.daily_budget && (
                    <span className="text-sm font-medium text-gray-700">${(c.daily_budget / 100).toFixed(0)}/day</span>
                  )}
                  <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                    c.status === 'active' ? 'bg-green-100 text-green-700' :
                    c.status === 'draft' ? 'bg-blue-100 text-blue-700' :
                    c.status === 'paused' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-gray-100 text-gray-700'
                  }`}>
                    {c.status}
                  </span>
                </div>
              </div>

              {c.targeting && Object.keys(c.targeting).length > 0 && (
                <div className="mt-3 border-t pt-3">
                  <p className="text-xs text-gray-400 mb-1">Targeting</p>
                  <div className="flex flex-wrap gap-1">
                    {Object.entries(c.targeting).map(([key, val]) => (
                      <span key={key} className="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-600">
                        {key}: {Array.isArray(val) ? (val as string[]).join(', ') : String(val)}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {c.created_at && (
                <p className="mt-2 text-xs text-gray-400">Created: {new Date(c.created_at).toLocaleString()}</p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border bg-white p-4 shadow-sm">
      <p className="text-sm text-gray-500">{label}</p>
      <p className="mt-1 text-2xl font-bold">{value}</p>
    </div>
  );
}
